### ISSUE TITLE
remoteEP null su LoginAsync e altro ancora

### ISSUE THREAD

**Issue by ontorder** [ontorder/CoreFTP#1]
ci sono ancora vari errori che infestano sto package

```
Content ingestion service general error
System.ArgumentNullException: Value cannot be null. (Parameter 'remoteEP')
at System.ArgumentNullException.Throw(String paramName)
at System.Net.Sockets.Socket.Connect(EndPoint remoteEP)
at CoreFtp.Infrastructure.Stream.FtpControlStream.ConnectSocketAsync(String host, Int32 port, CancellationToken token)
at CoreFtp.Infrastructure.Stream.FtpControlStream.ConnectStreamAsync(String host, Int32 port, CancellationToken token)
at CoreFtp.Infrastructure.Stream.FtpControlStream.ConnectStreamAsync(CancellationToken token)
at CoreFtp.Infrastructure.Stream.FtpControlStream.ConnectAsync(CancellationToken token)
at CoreFtp.FtpClient.LoginAsync()
at Planet.Garavot.ContentIngestion.ContentIngestionService.FtpExecActionAsync(Uri storeUri, Func`2 actionAsync) in /home/planet/zodiac-garavot-dev/src/content_ingestion/Planet.Garavot.ContentIngestion/Planet/Garavot/ContentIngestion/ContentIngestionService.cs:line 607
at Planet.Garavot.ContentIngestion.ContentIngestionService.FtpListAsync(Uri storeUri, Nullable`1 ftpLastModifiedThreshold) in /home/planet/zodiac-garavot-dev/src/content_ingestion/Planet.Garavot.ContentIngestion/Planet/Garavot/ContentIngestion/ContentIngestionService.cs:line 105
at Planet.Garavot.ContentIngestion.ContentIngestionService.GetStorageFilesAsync(ContentIngestionStorageSettings storageSettings) in /home/planet/zodiac-garavot-dev/src/content_ingestion/Planet.Garavot.ContentIngestion/Planet/Garavot/ContentIngestion/ContentIngestionService.cs:line 192
at Planet.Garavot.ContentIngestion.ContentIngestionBackgroundService.IngestNewFilesAsync(ContentIngestionStorageSettings storageSettings, CancellationToken cancellationToken) in /home/planet/zodiac-garavot-dev/src/content_ingestion/Planet.Garavot.ContentIngestion/Planet/Garavot/ContentIngestion/ContentIngestionBackgroundService.cs:line 212

```
```
Content ingestion service general error
System.IO.IOException: Unable to read data from the transport connection: Connection timed out.
---> System.Net.Sockets.SocketException (110): Connection timed out
at System.Net.Sockets.NetworkStream.Read(Byte[] buffer, Int32 offset, Int32 count)
--- End of inner exception stack trace ---
at System.Net.Sockets.NetworkStream.Read(Byte[] buffer, Int32 offset, Int32 count)
at CoreFtp.Infrastructure.Stream.FtpControlStream.ReadLine(Encoding encoding, CancellationToken token)
at CoreFtp.Infrastructure.Stream.FtpControlStream.ReadLines(CancellationToken token)+MoveNext()
at CoreFtp.Infrastructure.Stream.FtpControlStream.GetResponseAsync(CancellationToken token)
at CoreFtp.FtpClient.ListFilesAsyncEnum(Nullable`1 sortBy)+MoveNext()
at CoreFtp.FtpClient.ListFilesAsyncEnum(Nullable`1 sortBy)+System.Threading.Tasks.Sources.IValueTaskSource<System.Boolean>.GetResult()
at Planet.Garavot.ContentIngestion.ContentIngestionService.<>c__DisplayClass17_0.<<FtpListAsync>b__0>d.MoveNext() in /home/planet/zodiac-garavot-dev/src/content_ingestion/Planet.Garavot.ContentIngestion/Planet/Garavot/ContentIngestion/ContentIngestionService.cs:line 103
--- End of stack trace from previous location ---
at Planet.Garavot.ContentIngestion.ContentIngestionService.<>c__DisplayClass17_0.<<FtpListAsync>b__0>d.MoveNext() in /home/planet/zodiac-garavot-dev/src/content_ingestion/Planet.Garavot.ContentIngestion/Planet/Garavot/ContentIngestion/ContentIngestionService.cs:line 103
--- End of stack trace from previous location ---
at Planet.Garavot.ContentIngestion.ContentIngestionService.FtpExecActionAsync(Uri storeUri, Func`2 actionAsync) in /home/planet/zodiac-garavot-dev/src/content_ingestion/Planet.Garavot.ContentIngestion/Planet/Garavot/ContentIngestion/ContentIngestionService.cs:line 607
at Planet.Garavot.ContentIngestion.ContentIngestionService.FtpExecActionAsync(Uri storeUri, Func`2 actionAsync) in /home/planet/zodiac-garavot-dev/src/content_ingestion/Planet.Garavot.ContentIngestion/Planet/Garavot/ContentIngestion/ContentIngestionService.cs:line 607
at Planet.Garavot.ContentIngestion.ContentIngestionService.FtpListAsync(Uri storeUri, Nullable`1 ftpLastModifiedThreshold) in /home/planet/zodiac-garavot-dev/src/content_ingestion/Planet.Garavot.ContentIngestion/Planet/Garavot/ContentIngestion/ContentIngestionService.cs:line 105
at Planet.Garavot.ContentIngestion.ContentIngestionService.GetStorageFilesAsync(ContentIngestionStorageSettings storageSettings) in /home/planet/zodiac-garavot-dev/src/content_ingestion/Planet.Garavot.ContentIngestion/Planet/Garavot/ContentIngestion/ContentIngestionService.cs:line 192
at Planet.Garavot.ContentIngestion.ContentIngestionBackgroundService.IngestNewFilesAsync(ContentIngestionStorageSettings storageSettings, CancellationToken cancellationToken) in /home/planet/zodiac-garavot-dev/src/content_ingestion/Planet.Garavot.ContentIngestion/Planet/Garavot/ContentIngestion/ContentIngestionBackgroundService.cs:line 212
```

**Comment by ontorder** [comment]
c'è già un log di debug in FtpControlStream.Connect..., posso provare ad abilitarlo per specificatamente quella classe credo
...però vedo che dopo chiama dns resolver per ottenere indirizzo da host:port... potrei saltarlo se si tratta di un ip magari
